apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgres
spec:
  capacity:
    storage: 1Gi              # Size of the storage

  accessModes:
    - ReadWriteOnce           # Only one pod can read/write at a time (fine for Postgres)

  persistentVolumeReclaimPolicy: Retain   # Keep data even if PVC is deleted

  storageClassName: standard  # Must match PVC's storageClassName

  hostPath:
    path: /mnt/data/postgres  # Physical path on minikube node